---
title: "UV Stuff"
output: html_notebook
---

Goal here is to take a first pass look at the UV data

```{r}
source(here::here("Initial_Processing.R"))
```

```{r}
nonOyster_uv <- nonOyster_wm %>%
  filter(Info1 == "UV") %>%
  mutate(InfoUV = recode(InfoUV, Ctrl = "Control")) %>%
  mutate(`Brood#` = if_else(DayN == 0, "Combined", `Brood#`)) %>%
  mutate(Info2 = case_when(
    `Brood#` == "21-05" ~ "MainUVCrash",
    `Brood#` == "21-65" ~ "Main2",
    TRUE ~ Info2
  )) %>%
  identity()
```

```{r}
BactAbun_UV <- nonOyster_uv %>%
  group_by(Sample0) %>%
  summarise(ratio = sum(ratio)) %>%
  left_join(metadata, by = "Sample0") %>%
  mutate(InfoUV = recode(InfoUV, Ctrl = "Control")) %>%
  mutate(`Brood#` = if_else(DayN == 0, "Combined", `Brood#`)) %>%
  mutate(Info2 = case_when(
    `Brood#` == "21-05" ~ "MainUVCrash",
    `Brood#` == "21-65" ~ "Main2",
    TRUE ~ Info2
  )) %>%
  identity()

head(BactAbun_UV)
```

```{r}
BactAbun_UV %>% 
  select(contains("Info"), DayN, `Brood#`)
```


```{r}
BactAbun_UV %>%
  filter(Info2 == "Exp") %>%
  arrange(DayN) %>%
  #mutate(`Brood#` = if_else(DayN == 0, "Combined", `Brood#`)) %>%
  #filter(DayN != 0) %>%
  #mutate(DayN = if_else(DayN == 0, 1, DayN)) %>%
  #mutate(Info2 = forcats::fct_relevel(Info2, c("Best", "Ok", "Poor", "NoSurvivors"))) %>%
  ggplot(aes(x = as.numeric(DayN), y = log10(ratio), color = InfoUV, group = `Brood#`)) + geom_point() + scale_color_manual(values = c("black", "purple", "orange", "red")) + geom_path() +
  scale_x_continuous(breaks = c(1:20)) %>%
  identity()
```

```{r}
BactAbun_UV %>%
  #mutate(`Brood#` = if_else(DayN == 0, "Combined", `Brood#`)) %>%
  #filter(Info2 == "Exp") %>%
  #filter(DayN != 0) %>%
  #mutate(DayN = if_else(DayN == 0, 1, DayN)) %>%
  #mutate(Info2 = forcats::fct_relevel(Info2, c("Best", "Ok", "Poor", "NoSurvivors"))) %>%
  ggplot(aes(x = as.numeric(DayN), y = log10(ratio), shape = Info2, color = InfoUV, group = `Brood#`)) + geom_point() + scale_color_manual(values = c("black", "purple", "orange", "red")) + geom_path() +
  scale_x_continuous(breaks = c(1:20)) %>%
  identity()
```

```{r}
taxon_uv_plot <- function(df){
  df %>%
    ggplot(aes(x = as.numeric(DayN), y = log10(ratio + 10^-4), shape = Info2, color = InfoUV, fill = InfoUV, group = `Brood#`)) + geom_point() +
    scale_color_manual(values = c("black", "purple", "orange", "red")) +
    scale_fill_manual(values = c("black", "purple", "orange", "red")) +
    geom_path() +
  scale_x_continuous(breaks = c(seq(from = 3, to = 21, by = 2))) + facet_wrap(~GlomLevel, nrow = 1) +
  labs(x = "Day", y = "log10(o/h)") + theme_bw() +
    scale_shape_manual(values = c(Exp = 21,  MainUVCrash = 24, Main2 = 25))
}
```

```{r}
nonOyster_uv %>% group_taxa(Kingdom) %>%
  ungroup %>% filter(Kingdom != "Archaea") %>%
  taxon_uv_plot()
```
```{r}
nonOyster_uv %>%
group_taxa(Phylum) %>%
  keep_common(fraction = .3, minhits = 5) %>%
  filter(Kingdom == "Eukaryota") %>%
  taxon_uv_plot() +
  theme_bw(base_size = 14)
```
```{r}
nonOyster_uv %>%
group_taxa(Phylum) %>%
  keep_common(fraction = .3, minhits = 5) %>%
  filter(Kingdom == "Bacteria") %>%
  taxon_uv_plot() +
  theme_bw(base_size = 14) +
  theme(strip.text = element_text(size = 9))
```

### Ordination?
All microbes
```{r}
uv_ca_plot <- function(df){
  ratioDf_UV <- df %>%
  select(Sample0, ASV, ratio) %>%
  pivot_wider(names_from = ASV, values_from = ratio, values_fill = 0) %>%
  column_to_rownames("Sample0") %>%
  identity()

uv_ca <- cca(sqrt(ratioDf_UV))
#plot(uv_ca)
uv_ca_scores <- fortify(uv_ca, display = "wa", axes = 1:6) %>%
  rename(Sample0 = Label)


caDfUV <- BactAbun_UV %>%
  left_join(uv_ca_scores, by = "Sample0")

caDfUV %>%
  #filter(!Info2 %in% c("Charcoal", "Unknown")) %>%
  #mutate(Info2 = forcats::fct_relevel(Info2, c("Best", "Ok", "Poor", "NoSurvivors"))) %>%
  select(DayN, Info2, InfoUV, starts_with("CA"), `Brood#`) %>%
  pivot_longer(cols = starts_with("CA"), names_to = "CA_Axis", values_to = "CA_Score") %>%
  ggplot(aes(x = as.numeric(DayN), y = CA_Score, shape = Info2, color = InfoUV, group = `Brood#`)) + geom_point() + scale_color_manual(values = c("black", "purple", "orange", "red")) + geom_path() +
  scale_x_continuous(breaks = c(1:20)) +
  facet_wrap(~CA_Axis)
}

nonOyster_uv %>%
  keep_common() %>%
uv_ca_plot()
```
Bacteria only
```{r}
nonOyster_uv %>%
  filter(Kingdom == "Bacteria") %>%
  keep_common() %>%
uv_ca_plot()
```
## Constrained ordination

```{r}
ratioDf_UV <- nonOyster_uv %>% keep_common() %>%
  #filter(Kingdom == "Bacteria")  %>%
  select(Sample0, ASV, ratio) %>%
  pivot_wider(names_from = ASV, values_from = ratio, values_fill = 0) %>%
  column_to_rownames("Sample0") %>%
  identity()

cca1 <- cca(sqrt(ratioDf_UV) ~ InfoUV , data = BactAbun_UV )

#plot(cca1)
anova(cca1)
```

```{r}
cca2 <- cca(sqrt(ratioDf_UV) ~ InfoUV + Info2 + DayN, data = BactAbun_UV )
anova(cca2, by = "margin")
```
```{r}
plot(cca2)
```
```{r}
uv_scores <- fortify(cca2, display = "wa") %>% rename(Sample0 = Label)
uv_cn0 <- fortify(cca2, display = "cn")
uvDf <- BactAbun_UV %>% left_join(uv_scores, by = "Sample0")
```

```{r}
uvDf %>%
  mutate(DayInfo = recode(as.factor(DayN), `0` = "Exp Day 0",
                          `1` = "Exp Day 1",
                          `3` = "Exp Day 3",
                          `4` = "Main UV Crash",
                          `5` = "Main2 No Crash")) %>%
  ggplot(aes(x = CCA1, y = CCA2, fill = InfoUV, shape = DayInfo)) + geom_point(size = 3, alpha = 1, stroke = 1) +
  #geom_text(aes(x = CCA1, y = CCA2, label = Label), color = "black", data = uv_cn0 , inherit.aes = FALSE) +
  theme_bw(base_size = 14) + scale_fill_manual(values = c(Control = "black", UV = "purple")) +
  scale_shape_manual(values = c(21:25)) +
  scale_color_manual(values = c("black", "blue", "green", "yellow", "red"))  +
  labs(x = paste0("CCA1", " (19%)"), y = paste0("CCA2 (14%)")) +
  guides(fill = guide_legend(override.aes = list(shape = 21)))
```

With eukaryotes excluded when I comment in that one line.

```{r}
cca2$CCA$eig/cca2$tot.chi
sum(cca2$CCA$eig/cca2$tot.chi)
```

# Metadata

```{r}
library(readxl)
metaSteff <- read_excel(here("Hatchery_UVexperiment_All", "ExptData.xlsx"))
```

Survival
```{r fig.height = 2.5, fig.width= 3.5}
library(forcats)
metaSteff %>%
  mutate(Project = fct_relevel(Project, "Main UV Crash")) %>%
  ggplot(aes(x = Project, y = Fraction, color = Treatment)) + geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c(Ctrl = "Black", UV = "Purple")) +
  labs(y = "Fraction Surviving") +
  theme_bw(base_size = 14)
```
DAPI Counts
```{r}
DAPI <- metaSteff %>%
  filter(Project == "Exp") %>%
  select(Treatment, Replicate, contains("DAPI")) %>%
  pivot_longer(contains("DAPI"), values_to = "abundance") %>%
  mutate(day = parse_number(name)) %>% ungroup() %>% 
  #mutate(day = as.character(day)) %>%
  identity()
DAPI
```
```{r fig.height = 2.5, fig.width= 4}
ggplot(DAPI, aes(x = (day), y = abundance, color = Treatment, group_by = Replicate)) + geom_point() +
  geom_path() +
  scale_color_manual(values = c(Ctrl = "Black", UV = "Purple")) +
  labs(y = "microbial abundance in water \n (cells/ml)", x = "TimePoint") +
  scale_x_continuous(breaks = c(1,3)) +
  theme_bw(base_size = 14)
```

